config/routes.rb
Rails.application.routes.draw do
  resources :products
  root 'site#index'
  get '/about' => 'site#about'
end

#  Prefix Verb   URI Pattern                  Controller#Action
#     products GET    /products(.:format)          products#index
#              POST   /products(.:format)          products#create
#  new_product GET    /products/new(.:format)      products#new
# edit_product GET    /products/:id/edit(.:format) products#edit
#      product GET    /products/:id(.:format)      products#show
#              PATCH  /products/:id(.:format)      products#update
#              PUT    /products/:id(.:format)      products#update
#              DELETE /products/:id(.:format)      products#destroy

app/models/car.rb
class Car < ActiveRecord::Base
end

app/models/product.rb
class Product < ActiveRecord::Base

  validates :name, presence: true

  # older version
  # validate_presence_of :name
  # other validations
  # validates :email, uniqueness: true
  # validates :password, min_length: 6


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :find_product, only: [:show, :edit, :update, :destroy]
  # The index action
  # This should list all of our products
  #index.html.erb
  def index
    @products = Product.all
  end

  # This should find a particular product
  def show
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      flash[:notice] = 'Good job! You did it.'
      redirect_to products_path
    else
      flash[:alert] = 'Bad job! You failed.'
      render :new
    end
  end

  def edit
  end

  def update
    if @product.update_attributes(product_params)
      redirect_to products_path
      # update_attributes use vs update
    else
      render :edit
    end
  end

  def destroy
    @product.destroy
    redirect_to products_path
  end

  private
  # 3 types public, private, protected
  # define a private method
  # use strong parameters
  def product_params
    params.require(:product).permit(:name)
  end

  def find_product
      @product = Product.find(params[:id])
  end


end

app/controllers/site_controller.rb
class SiteController < ApplicationController

  # action_name.format.template_engine
  # index.html.erb
  # index.json.jbuilder
  # index.xml.builder
  # index.pdf.erb
  def index
    @products = Product.all
    @cars = Car.all
  end

  def about

  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def show_notice_message
      unless flash.empty?
      [:notice, :alert].each do |key|
        return content_tag(:div, flash[key],
        class: "flash-#{key}") if flash[key].present?
      end
    end
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DplStore</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div id="wrapper">
    <header>
      <nav>
        <%= link_to('Home Page', root_path) %>
        <span>&nbsp;|&nbsp;</span>
        <%= link_to('View Products', products_path) %>
        <span>&nbsp;|&nbsp;</span>
        <%= link_to('About DPL Store', about_path) %>
      </nav>
    </header>
    <%= show_notice_message %>
    <section id="main-content">
      <%= yield %>
    </section>
    <footer>
      copyright &copy; <%= Time.now.year %>
    </footer>
  </div>
</body>
</html>

app/views/products/edit.html.erb
<h1>Edit <%= @product.name %></h1>

<%= form_for(@product) do |f|%>
  <%= f.label(:name) %>
  <%= f.text_field(:name) %>
  <%= f.submit('Update') %>
<% end %>

app/views/products/index.html.erb
<%= link_to('Create a new product', new_product_path) %>

<h1>Showing <%= pluralize(@products.count, 'Product') %></h1>
<ul id="products">
<% @products.each do |product| %>
  <li class="<%= cycle('even', 'odd') %>">
    <%= link_to(product.name, product_path(product.id)) %>
    <%= number_to_currency(product.price) %>
    -- <%= link_to('edit', edit_product_path(product.id)) %>
    -- <%= link_to('delete', product_path(product.id),
    method: :delete, 'data-confirm' => 'Are you sure?') %>
    Created <%= time_ago_in_words(product.created_at) %> ago
  </li>
<% end %>
</ul>

app/views/products/new.html.erb
<h1>Make a new product</h1>

<%= form_for(@product) do |f| %>
  <div>
    <%= f.label(:name) %>
    <%= f.text_field(:name) %>
  </div>
  <div>
    <%= f.submit('Save Product') %>
  </div>
<% end %>

app/views/products/show.html.erb
<h1><%= @product.name %></h1>
<h3><%=number_to_currency(@product.price) %></h3>
<p>Sku: <%= @product.sku %></p>
<div>
  <%= @product.description %>
</div>

<%= link_to('&laquo; Back to all products'.html_safe, products_path) %>

app/views/site/about.html.erb
<h1>About DPL Store</h1>

<p>Bacon ipsum dolor sit amet pastrami kevin pig pancetta bacon. Tri-tip swine ham pork chop tail sausage drumstick leberkas.
Beef prosciutto kielbasa andouille porchetta spare ribs brisket chuck frankfurter pancetta ham.
Pancetta turkey meatball t-bone jerky, spare ribs pork frankfurter leberkas short loin boudin landjaeger jowl capicola turducken.
Pastrami short loin biltong, prosciutto pork belly kevin brisket rump corned beef ribeye landjaeger sirloin.</p>

<p>Bacon ipsum dolor sit amet pastrami kevin pig pancetta bacon. Tri-tip swine ham pork chop tail sausage drumstick leberkas.
Beef prosciutto kielbasa andouille porchetta spare ribs brisket chuck frankfurter pancetta ham.
Pancetta turkey meatball t-bone jerky, spare ribs pork frankfurter leberkas short loin boudin landjaeger jowl capicola turducken.
Pastrami short loin biltong, prosciutto pork belly kevin brisket rump corned beef ribeye landjaeger sirloin.</p>

app/views/site/index.html.erb
<h1>Welcome To The DPL Store!</h1>
<%= image_tag('ruby.jpg', size: '100x100') %>

<div class="left-column">
  <h2>Our Products</h2>
  <% @products.each do |product| %>
    <div class="product">
      <%= product.name %>
    </div>
  <% end %>
</div>

<div class="right-column">
  <h2>Our Cars</h2>
  <% @cars.each do |car| %>
    <div class="car">
      <%= car.year %> <%= car.make %> <%= car.model %>
    </div>
    <% end %>
  </div>
  <br clear="all" />